# EMBEDDED SERVER CONFIGURATION
server:
  port: ${PORT:8082}
  use-forward-headers: true
  error.whitelabel.enabled: false
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - text/html
      - text/css
      - text/plain
      - text/xml
      - application/json
      - application/javascript
  servlet:
    context-path: /auth

# PROFILES
spring:
  application.name: zx-authserver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/rad
    username: dbadmin
    password: P@ssp0rt
    driverClassName: org.postgresql.Driver

# RabbitMQ datasource
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:appspace-auth}
    password: ${RABBITMQ_PASS:P@ssp0rt}

# LOGGING
logging:
  level:
    org:
      springframework:
        security: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG

aossia:
  rad:
    passwordRecovery:
      confirm:
        subject: password recovery confirmation
    registration:
      scopes: ${SCOPES}
      confirm:
        from: ${spring.application.name}@zonta.tech
        subject: registration confirmation

# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:aossia-rad-discovery}:8761/eureka/

---

spring:
  profiles: standalone

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:zx_users}?useUnicode=yes&characterEncoding=UTF-8
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:appspace-auth}
    password: ${RABBITMQ_PASS:P@ssp0rt}

# EUREKA
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
