server:
  port: ${port:8081}
  error.whitelabel.enabled: false
  compression:
    enabled: true
    min-response-size: 102400000
    mime-types:
      - text/html
      - text/css
      - text/plain
      - text/xml
      - application/json
      - application/javascript
  servlet:
    context-path: /

spring:
  application.name: dtsp-api
